# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hikari/Dokumenty/personal_programs/messenger

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hikari/Dokumenty/personal_programs/messenger

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hikari/Dokumenty/personal_programs/messenger/CMakeFiles /home/hikari/Dokumenty/personal_programs/messenger//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hikari/Dokumenty/personal_programs/messenger/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named messenger

# Build rule for target.
messenger: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 messenger
.PHONY : messenger

# fast build rule for target.
messenger/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/build
.PHONY : messenger/fast

#=============================================================================
# Target rules for targets named messenger_server

# Build rule for target.
messenger_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 messenger_server
.PHONY : messenger_server

# fast build rule for target.
messenger_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_server.dir/build.make CMakeFiles/messenger_server.dir/build
.PHONY : messenger_server/fast

server/Client.o: server/Client.cpp.o
.PHONY : server/Client.o

# target to build an object file
server/Client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_server.dir/build.make CMakeFiles/messenger_server.dir/server/Client.cpp.o
.PHONY : server/Client.cpp.o

server/Client.i: server/Client.cpp.i
.PHONY : server/Client.i

# target to preprocess a source file
server/Client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_server.dir/build.make CMakeFiles/messenger_server.dir/server/Client.cpp.i
.PHONY : server/Client.cpp.i

server/Client.s: server/Client.cpp.s
.PHONY : server/Client.s

# target to generate assembly for a file
server/Client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_server.dir/build.make CMakeFiles/messenger_server.dir/server/Client.cpp.s
.PHONY : server/Client.cpp.s

server/main.o: server/main.cpp.o
.PHONY : server/main.o

# target to build an object file
server/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_server.dir/build.make CMakeFiles/messenger_server.dir/server/main.cpp.o
.PHONY : server/main.cpp.o

server/main.i: server/main.cpp.i
.PHONY : server/main.i

# target to preprocess a source file
server/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_server.dir/build.make CMakeFiles/messenger_server.dir/server/main.cpp.i
.PHONY : server/main.cpp.i

server/main.s: server/main.cpp.s
.PHONY : server/main.s

# target to generate assembly for a file
server/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_server.dir/build.make CMakeFiles/messenger_server.dir/server/main.cpp.s
.PHONY : server/main.cpp.s

src/App.o: src/App.cpp.o
.PHONY : src/App.o

# target to build an object file
src/App.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/App.cpp.o
.PHONY : src/App.cpp.o

src/App.i: src/App.cpp.i
.PHONY : src/App.i

# target to preprocess a source file
src/App.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/App.cpp.i
.PHONY : src/App.cpp.i

src/App.s: src/App.cpp.s
.PHONY : src/App.s

# target to generate assembly for a file
src/App.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/App.cpp.s
.PHONY : src/App.cpp.s

src/ColorTile.o: src/ColorTile.cpp.o
.PHONY : src/ColorTile.o

# target to build an object file
src/ColorTile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/ColorTile.cpp.o
.PHONY : src/ColorTile.cpp.o

src/ColorTile.i: src/ColorTile.cpp.i
.PHONY : src/ColorTile.i

# target to preprocess a source file
src/ColorTile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/ColorTile.cpp.i
.PHONY : src/ColorTile.cpp.i

src/ColorTile.s: src/ColorTile.cpp.s
.PHONY : src/ColorTile.s

# target to generate assembly for a file
src/ColorTile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/ColorTile.cpp.s
.PHONY : src/ColorTile.cpp.s

src/Connection.o: src/Connection.cpp.o
.PHONY : src/Connection.o

# target to build an object file
src/Connection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/Connection.cpp.o
.PHONY : src/Connection.cpp.o

src/Connection.i: src/Connection.cpp.i
.PHONY : src/Connection.i

# target to preprocess a source file
src/Connection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/Connection.cpp.i
.PHONY : src/Connection.cpp.i

src/Connection.s: src/Connection.cpp.s
.PHONY : src/Connection.s

# target to generate assembly for a file
src/Connection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/Connection.cpp.s
.PHONY : src/Connection.cpp.s

src/Renderer.o: src/Renderer.cpp.o
.PHONY : src/Renderer.o

# target to build an object file
src/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/Renderer.cpp.o
.PHONY : src/Renderer.cpp.o

src/Renderer.i: src/Renderer.cpp.i
.PHONY : src/Renderer.i

# target to preprocess a source file
src/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/Renderer.cpp.i
.PHONY : src/Renderer.cpp.i

src/Renderer.s: src/Renderer.cpp.s
.PHONY : src/Renderer.s

# target to generate assembly for a file
src/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/Renderer.cpp.s
.PHONY : src/Renderer.cpp.s

src/Tile.o: src/Tile.cpp.o
.PHONY : src/Tile.o

# target to build an object file
src/Tile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/Tile.cpp.o
.PHONY : src/Tile.cpp.o

src/Tile.i: src/Tile.cpp.i
.PHONY : src/Tile.i

# target to preprocess a source file
src/Tile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/Tile.cpp.i
.PHONY : src/Tile.cpp.i

src/Tile.s: src/Tile.cpp.s
.PHONY : src/Tile.s

# target to generate assembly for a file
src/Tile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/Tile.cpp.s
.PHONY : src/Tile.cpp.s

src/Tiles.o: src/Tiles.cpp.o
.PHONY : src/Tiles.o

# target to build an object file
src/Tiles.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/Tiles.cpp.o
.PHONY : src/Tiles.cpp.o

src/Tiles.i: src/Tiles.cpp.i
.PHONY : src/Tiles.i

# target to preprocess a source file
src/Tiles.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/Tiles.cpp.i
.PHONY : src/Tiles.cpp.i

src/Tiles.s: src/Tiles.cpp.s
.PHONY : src/Tiles.s

# target to generate assembly for a file
src/Tiles.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/Tiles.cpp.s
.PHONY : src/Tiles.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger.dir/build.make CMakeFiles/messenger.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... messenger"
	@echo "... messenger_server"
	@echo "... server/Client.o"
	@echo "... server/Client.i"
	@echo "... server/Client.s"
	@echo "... server/main.o"
	@echo "... server/main.i"
	@echo "... server/main.s"
	@echo "... src/App.o"
	@echo "... src/App.i"
	@echo "... src/App.s"
	@echo "... src/ColorTile.o"
	@echo "... src/ColorTile.i"
	@echo "... src/ColorTile.s"
	@echo "... src/Connection.o"
	@echo "... src/Connection.i"
	@echo "... src/Connection.s"
	@echo "... src/Renderer.o"
	@echo "... src/Renderer.i"
	@echo "... src/Renderer.s"
	@echo "... src/Tile.o"
	@echo "... src/Tile.i"
	@echo "... src/Tile.s"
	@echo "... src/Tiles.o"
	@echo "... src/Tiles.i"
	@echo "... src/Tiles.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

